JROC_NAME=J-Roc
JROC_PLATFORM=XCore
JROC_API=1.0

CORE=enabled
MEMORY=enabled
INTERRUPTS=enabled
PROCESS=enabled
STORAGE=enabled
NETWORK=enabled
SECURITY=enabled
SERVICES=enabled
USERSPACE=enabled
DESKTOP=enabled
APPS=enabled
SDK=enabled
PACKAGES=enabled
DEVELOPER=enabled

FRONTEND=enabled
BACKEND=enabled

AI=interface
CLOUD=interface

INSTALLER=enabled
RECOVERY=enabled
DIAGNOSTICS=enabled
ROLLBACK=enabled
